#!/bin/bash

DATE=$(date +%Y%m%d%H%M%S)
docker tag $IMAGE_NAME $DOCKER_REPO:6.6.0-$DATE
docker tag $IMAGE_NAME $DOCKER_REPO:6.6.0
docker tag $IMAGE_NAME $DOCKER_REPO:6
docker push $DOCKER_REPO:6.6.0-$DATE
docker push $DOCKER_REPO:6.6.0
docker push $DOCKER_REPO:6
